package com.rumivetai.app;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.text.InputType;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
    LinearLayout root, content; TextView title; SharedPreferences prefs;
    final int GREEN=Color.rgb(23,107,91), BG=Color.rgb(248,250,249);
    ArrayList<JSONObject> diseases=new ArrayList<>(), labs=new ArrayList<>(), drugs=new ArrayList<>(), protocols=new ArrayList<>();
    int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+0.5f);}
    TextView tv(String s,int sp){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(Color.DKGRAY);t.setPadding(dp(4),dp(5),dp(4),dp(5));return t;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
    EditText edit(String hint){EditText e=new EditText(this);e.setHint(hint);e.setPadding(dp(12),dp(8),dp(12),dp(8));e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);return e;}
    @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("rumivet",0);loadData();showHome();}
    void loadData(){diseases=load("diseases.json");labs=load("labs.json");drugs=load("drugs.json");protocols=load("protocols.json");}
    ArrayList<JSONObject> load(String file){ArrayList<JSONObject> a=new ArrayList<>();try{InputStream in=getAssets().open(file);BufferedReader r=new BufferedReader(new InputStreamReader(in));StringBuilder s=new StringBuilder();String l;while((l=r.readLine())!=null)s.append(l);JSONArray j=new JSONArray(s.toString());for(int i=0;i<j.length();i++)a.add(j.getJSONObject(i));}catch(Exception e){}return a;}
    void base(String name){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(10),dp(6),dp(10),dp(6));bar.setBackgroundColor(GREEN);Button back=btn("‹");back.setTextColor(Color.WHITE);back.setBackgroundColor(Color.TRANSPARENT);back.setOnClickListener(v->showHome());bar.addView(back,new LinearLayout.LayoutParams(dp(55),dp(55)));title=tv(name,21);title.setTextColor(Color.WHITE);bar.addView(title,new LinearLayout.LayoutParams(0,dp(55),1));root.addView(bar);ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(16),dp(16),dp(16),dp(24));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    void showHome(){base("RumiVet AI");content.addView(tv("Ruminant Veterinary Clinical Decision Support",22));content.addView(tv("Cattle • Buffalo • Sheep • Goat • Calf • Lamb • Kid",14));
      addCard("🩺 Clinical Diagnosis","Structured case entry + knowledge-based differentials",v->clinical());
      addCard("🧪 Laboratory Analysis","Reference-aware interpretation for common tests",v->lab());
      addCard("💊 Treatment & Dose Calculator","Treatment protocols + weight-based calculation",v->dose());
      addCard("📚 Disease Knowledge","Search disease signs, diagnostics, differentials and priority",v->diseaseBrowser());
      addCard("💉 Drug Database","Browse safety-focused drug/product guidance",v->drugBrowser());
      addCard("📋 Treatment Protocols","Condition-specific stabilization and treatment principles",v->protocolBrowser());
      addCard("🐄 Animal Registry","Save local animal records",v->animals());
      addCard("📂 Saved Cases","Review saved clinical cases",v->saved());
      addCard("🚨 Emergency Guide","Immediate red flags and stabilization reminders",v->emergency());
      addCard("🔐 Privacy & Safety","Offline data, clinical safety and implementation notes",v->privacy());
      content.addView(tv("Clinical safety: this is decision-support software. Confirm diagnosis, product label, dose, route, contraindications and food-animal withdrawal periods before treatment.",13));}
    void addCard(String h,String s,View.OnClickListener l){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(14),dp(12),dp(14),dp(12));box.setBackgroundColor(Color.WHITE);TextView a=tv(h,18);a.setTextColor(GREEN);box.addView(a);box.addView(tv(s,13));box.setOnClickListener(l);content.addView(box,new LinearLayout.LayoutParams(-1,dp(94)));Space sp=new Space(this);content.addView(sp,new LinearLayout.LayoutParams(1,dp(8)));}
    void searchList(String titleText,String hint,ArrayList<JSONObject> data,String[] fields){base(titleText);EditText q=edit(hint);q.setSingleLine(true);content.addView(q);LinearLayout results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);content.addView(results);Runnable refresh=()->{results.removeAllViews();String term=q.getText().toString().toLowerCase(Locale.US);int count=0;for(JSONObject o:data){boolean ok=term.isEmpty();for(String f:fields)if(o.optString(f).toLowerCase(Locale.US).contains(term))ok=true;if(ok){count++;Button b=btn(o.optString(fields[0],"Record"));results.addView(b);b.setOnClickListener(v->detail(titleText,o));if(count>=100)break;}}if(count==0)results.addView(tv("No matching records.",15));};q.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){refresh.run();}public void afterTextChanged(android.text.Editable e){}});refresh.run();}
    void detail(String header,JSONObject o){base(header);StringBuilder s=new StringBuilder();Iterator<String> it=o.keys();while(it.hasNext()){String k=it.next();s.append(k.replace("_"," ").toUpperCase(Locale.US)).append(":\n").append(o.optString(k)).append("\n\n");}content.addView(tv(s.toString(),15));}
    void diseaseBrowser(){searchList("Disease Knowledge","Search disease, species, signs or diagnostics",diseases,new String[]{"name","species","signs","diagnostics","differentials"});}
    void drugBrowser(){searchList("Drug Database","Search generic name, class, species or indication",drugs,new String[]{"name","class","species","uses"});}
    void protocolBrowser(){searchList("Treatment Protocols","Search condition, species or priority",protocols,new String[]{"condition","species","priority","diagnostics","treatment_principles"});}
    void clinical(){base("Clinical Diagnosis");TextView result=tv("",15);EditText species=edit("Species (cattle/buffalo/sheep/goat)");EditText age=edit("Age / class");EditText temp=edit("Temperature (optional)");EditText signs=edit("Clinical signs / main complaint");EditText history=edit("History / feed change / duration / previous treatment");for(EditText e:new EditText[]{species,age,temp,signs,history})content.addView(e,new LinearLayout.LayoutParams(-1,dp(62)));Button analyze=btn("Analyze Case");content.addView(analyze);content.addView(result);analyze.setOnClickListener(v->{String r=diagnose(species.getText().toString(),signs.getText().toString(),history.getText().toString(),temp.getText().toString());result.setText(r);saveCase(species.getText().toString(),signs.getText().toString(),r);});}
    String diagnose(String sp,String sg,String hi,String te){String x=(sg+" "+hi).toLowerCase(Locale.US);StringBuilder r=new StringBuilder("Clinical decision-support output\n\n");if(x.contains("bloat")||x.contains("tympany")||x.contains("distended left")||x.contains("dyspnea")||x.contains("difficulty breathing"))r.append("⚠ URGENT: possible life-threatening bloat/respiratory compromise. Immediate examination is required.\n\n");ArrayList<String> hits=new ArrayList<>();for(JSONObject d:diseases){String corpus=(d.optString("name")+" "+d.optString("signs")+" "+d.optString("risk")+" "+d.optString("differentials")).toLowerCase(Locale.US);int score=0;for(String token:x.split("[^a-z0-9]+")){if(token.length()>3&&corpus.contains(token))score++;}if(score>0)hits.add(score+"|"+d.optString("name")+" — "+d.optString("diagnostics"));}Collections.sort(hits,Collections.reverseOrder());if(hits.isEmpty())r.append("No database match with the supplied terms. Add duration, appetite, feces, temperature, rumen motility, hydration, respiratory and reproductive findings.\n");else{r.append("Knowledge-base matches (not confirmed diagnoses):\n");int n=0;for(String h:hits){r.append("• ").append(h.substring(h.indexOf('|')+1)).append("\n");if(++n>=8)break;}}r.append("\nSuggested next steps:\n• Full physical examination and TPR\n• Hydration/perfusion and mucous membranes\n• Rumen motility and abdominal examination\n• CBC/chemistry/electrolytes when indicated\n• Fecal/milk/blood/other targeted tests according to syndrome\n• Review exact previous drug, concentration, dose, route and timing\n");return r.toString();}
    void lab(){base("Laboratory Analysis");Spinner test=new Spinner(this);String[] names={"Select test","Calcium (total)","Potassium","Magnesium","Glucose","PCV/HCT","Total protein","Sodium","Chloride","Urea nitrogen","Creatinine"};test.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,names));EditText species=edit("Species (Cow/Sheep/Goat/Buffalo) and age class");EditText val=edit("Measured value");TextView out=tv("",15);content.addView(test);content.addView(species);content.addView(val);Button b=btn("Interpret Result");content.addView(b);content.addView(out);b.setOnClickListener(v->out.setText(labInterpret(test.getSelectedItem().toString(),species.getText().toString(),val.getText().toString())));}
    String labInterpret(String test,String sp,String s){double v;try{v=Double.parseDouble(s.trim());}catch(Exception e){return "Enter a numeric result.";}String species=sp.toLowerCase(Locale.US);JSONObject match=null;for(JSONObject o:labs){if(o.optString("name").equalsIgnoreCase(test)&&species.contains(o.optString("species").toLowerCase(Locale.US))){match=o;break;}}if(match==null)for(JSONObject o:labs)if(o.optString("name").equalsIgnoreCase(test)){match=o;break;}if(match==null)return "No validated reference record found in the bundled database. Use the performing laboratory's species/age-specific interval.";double lo=match.optDouble("low",Double.NaN),hi=match.optDouble("high",Double.NaN);String interp=v<lo?"Below the bundled reference interval.":v>hi?"Above the bundled reference interval.":"Within the bundled reference interval.";return test+"\nSpecies record: "+match.optString("species")+"\nReference: "+lo+"–"+hi+" "+match.optString("unit")+"\n\nInterpretation: "+interp+"\n\n"+match.optString("note")+"\n\nUse the reporting laboratory's validated interval when available.";}
    void dose(){base("Treatment & Dose Calculator");EditText w=edit("Body weight (kg)");EditText d=edit("Dose (mg/kg)");EditText c=edit("Product concentration (mg/mL)");EditText extra=edit("Drug/product name and route (optional)");TextView out=tv("",17);content.addView(extra);content.addView(w);content.addView(d);content.addView(c);Button b=btn("Calculate");content.addView(b);content.addView(out);b.setOnClickListener(v->{try{double x=Double.parseDouble(w.getText().toString()),y=Double.parseDouble(d.getText().toString()),z=Double.parseDouble(c.getText().toString());if(x<=0||y<=0||z<=0)throw new Exception();out.setText(String.format(Locale.US,"Calculated dose: %.2f mg\nCalculated volume: %.2f mL\n\nFormula: kg × mg/kg ÷ mg/mL\n\nBefore administration verify the selected protocol/product label, maximum dose, route, interval, contraindications and milk/meat withdrawal.",x*y,(x*y)/z));}catch(Exception e){out.setText("Enter positive numeric weight, dose and concentration.");}});}
    void animals(){base("Animal Registry");EditText id=edit("Animal ID / ear tag");EditText species=edit("Species");EditText sex=edit("Sex / age");EditText notes=edit("Notes");for(EditText e:new EditText[]{id,species,sex,notes})content.addView(e);Button save=btn("Save Animal");content.addView(save);TextView list=tv("",15);content.addView(list);refreshAnimals(list);save.setOnClickListener(v->{if(id.getText().toString().trim().isEmpty())return;String old=prefs.getString("animals","");String line=id.getText()+" | "+species.getText()+" | "+sex.getText()+" | "+notes.getText();prefs.edit().putString("animals",old+line+"\n").apply();refreshAnimals(list);id.setText("");notes.setText("");});}
    void refreshAnimals(TextView l){String a=prefs.getString("animals","");l.setText(a.isEmpty()?"No animals saved yet.":"Saved animals:\n\n"+a);}
    void saved(){base("Saved Cases");String a=prefs.getString("cases","");content.addView(tv(a.isEmpty()?"No cases saved yet.":a,14));}
    void saveCase(String sp,String signs,String result){String s=prefs.getString("cases","");String stamp=new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.US).format(new Date());prefs.edit().putString("cases",s+"CASE "+stamp+" | "+sp+" | "+signs+"\n"+result+"\n--------------------\n").apply();}
    void emergency(){base("Emergency Guide");content.addView(tv("🚨 Immediate examination / stabilization may be required for:\n\n• Severe bloat/tympany with respiratory distress\n• Recumbency, collapse or shock\n• Severe dehydration\n• Persistent respiratory distress\n• Suspected severe hypocalcemia around parturition\n• Suspected poisoning/toxin exposure\n• Severe dystocia or prolapse with compromise\n• Acute neurologic signs\n• Severe systemic illness with deterioration\n\nAssess airway, breathing, circulation/perfusion, temperature and hydration. Use validated emergency protocols and local veterinary support.\n\nReportable/zoonotic disease suspects should be managed according to local authority requirements.",16));}
    void privacy(){base("Privacy & Safety");content.addView(tv("RumiVet AI implementation notes\n\n• Core knowledge files are bundled locally for offline use.\n• Clinical records in this prototype are stored in local app preferences; a production release should use encrypted database storage.\n• Production architecture should implement authentication, RBAC, organization/farm/animal/case permissions, audit logs, encrypted sync and controlled exports.\n• AI-generated suggestions must remain separate from veterinarian-confirmed diagnoses and lab-confirmed results.\n• Finalized clinical records should be immutable with amendment history.\n• Do not send private clinical data to an external AI service without an explicit privacy/legal policy and user authorization.\n• Never invent a drug dose, product concentration, withdrawal period or laboratory interval.\n• Verify food-animal withdrawal periods from the exact registered product and applicable jurisdiction.\n\nSee the included ARCHITECTURE.md, DATABASE_SCHEMA.md, SECURITY_PRIVACY.md and CLINICAL_SAFETY.md files for the production implementation plan.",15));}
}
